import Head from "next/head";
import SearchForm from "../components/Flights/SearchForm";
import AppLayout from "../components/Layout/AppLayout";
import Travel from "../components/Places/Travel";

export default function Home() {
  return (
    <AppLayout>
      <Head>
        <title>Booking App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center relative h-[700px] sm:h-[860px]'>
        <div className='bg-hero-pattern sm:bg-cover sm:bg-left bg-contain bg-no-repeat h-full sm:h-[599px] w-full'></div>
        <SearchForm />
      </main>
      <section className='flex flex-col mb-10 '>
        <div className='lg:w-[1232px] mx-6 sm:mx-auto mb-6 '>
          <h1 className='sm:text-4xl font-semibold mb-4'>
            Let's go places together
          </h1>
          <p className='mb-6 text-md'>
            Discover the latest offers and news and start planning your next
            trip with us.
          </p>
        </div>
        <div className='bg-section-map bg-contain sm:bg-cover bg-center mb-20  sm:mb-0 h-40 sm:h-[486px] w-full'></div>
      </section>
      {/* <Places /> */}
      <Travel />
    </AppLayout>
  );
}
