import Head from "next/head";
import LandingPage from "../components/LandingPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Booking App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LandingPage />
    </>
  );
}
